version: '3'


services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: maffin
      POSTGRES_PASSWORD: maffin
      POSTGRES_DB: maffin
    ports:
      - "5432:5432"


  django:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DEBUG: "False"
      DB_NAME: "maffin"
      DB_USER: "maffin"
      DB_PASSWORD: "maffin"
      DB_HOST: "postgres"
      DB_PORT: 5432