# Generated by Django 5.0.3 on 2024-03-23 18:28

import django.core.validators
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^[0-9]{4}[A-Z]$')])),
                ('location', models.IntegerField(verbose_name=myapp.models.Unique_location)),
                ('lifting_capacity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000)])),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up', models.IntegerField(verbose_name=myapp.models.Unique_location)),
                ('delivery', models.IntegerField(verbose_name=myapp.models.Unique_location)),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Unique_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=150)),
            ],
        ),
    ]
