# Generated by Django 5.0.3 on 2024-03-24 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_cargo_delivery_alter_cargo_pick_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unique_location',
            name='zip',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Пожалуйста, введите только цифры', regex='^[0-9]*$')]),
        ),
    ]
