# Generated by Django 5.0.3 on 2024-03-24 19:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_unique_location_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='pick_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_location', to='myapp.unique_location', validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')]),
        ),
    ]
