# Generated by Django 5.0.3 on 2024-03-24 19:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_cargo_pick_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='lifting_capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.RegexValidator(regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_location', to='myapp.unique_location', validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.RegexValidator(regex='^[0-9]*$')]),
        ),
    ]
