# Generated by Django 5.0.3 on 2024-03-25 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_car_lifting_capacity_alter_cargo_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unique_location', validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')]),
        ),
    ]
